-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 22:16:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema id10884474_catering
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id10884474_catering
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id10884474_catering` DEFAULT CHARACTER SET utf8mb4 ;
USE `id10884474_catering` ;

-- -----------------------------------------------------
-- Table `id10884474_catering`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`person` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`person` (
  `name` VARCHAR(30) NULL,
  `cnic` VARCHAR(30) NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `image` TEXT(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`address` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address_city` VARCHAR(50) NULL DEFAULT 'lahore',
  `address_town` VARCHAR(50) NULL,
  `address_street_no` INT(11) NULL DEFAULT NULL,
  `address_house_no` INT(11) NULL DEFAULT NULL,
  `person_id` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_address_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `id10884474_catering`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`number` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`number` (
  `number` VARCHAR(30) NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_number_active` TINYINT NULL DEFAULT 1,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_number_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_number_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `id10884474_catering`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`orderTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`orderTable` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`orderTable` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `total_amount` INT(11) NULL DEFAULT 0,
  `order_comments` TEXT NULL DEFAULT NULL,
  `total_person` INT NULL,
  `is_active` INT NULL DEFAULT 0,
  `destination_date` DATE NULL,
  `booking_date` DATE NULL,
  `destination_time` TIME(6) NULL,
  `address_id` INT(11) NOT NULL,
  `extre_charges` INT NULL,
  `person_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_address1_idx` (`address_id` ASC),
  INDEX `fk_order_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_order_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `id10884474_catering`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `id10884474_catering`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`dish_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`dish_type` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`dish_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`dish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`dish` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`dish` (
  `name` VARCHAR(30) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(300) NULL,
  `dish_type_id` INT NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_dish_type1_idx` (`dish_type_id` ASC),
  CONSTRAINT `fk_dish_dish_type1`
    FOREIGN KEY (`dish_type_id`)
    REFERENCES `id10884474_catering`.`dish_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`attribute` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`attribute` (
  `name` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `dish_id` INT NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_dish1_idx` (`dish_id` ASC),
  CONSTRAINT `fk_attribute_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `id10884474_catering`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`dish_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`dish_detail` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`dish_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `describe` TEXT(300) NULL,
  `price` INT NULL,
  `expire_date` DATETIME NULL,
  `quantity` INT NULL,
  `dish_id` INT NOT NULL,
  `orderTable_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dish_detail_dish1_idx` (`dish_id` ASC),
  INDEX `fk_dish_detail_orderTable1_idx` (`orderTable_id` ASC),
  CONSTRAINT `fk_dish_detail_dish1`
    FOREIGN KEY (`dish_id`)
    REFERENCES `id10884474_catering`.`dish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dish_detail_orderTable1`
    FOREIGN KEY (`orderTable_id`)
    REFERENCES `id10884474_catering`.`orderTable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`attribute_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`attribute_name` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`attribute_name` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL,
  `attribute_id` INT NOT NULL,
  `dish_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attribute_name_attribute1_idx` (`attribute_id` ASC),
  INDEX `fk_attribute_name_dish_detail1_idx` (`dish_detail_id` ASC),
  CONSTRAINT `fk_attribute_name_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `id10884474_catering`.`attribute` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attribute_name_dish_detail1`
    FOREIGN KEY (`dish_detail_id`)
    REFERENCES `id10884474_catering`.`dish_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`user` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(30) NULL,
  `person_id` INT(11) NOT NULL,
  `isExpire` DATETIME NULL DEFAULT NULL,
  `isowner` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_user_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `id10884474_catering`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`payment` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `nameCustomer` VARCHAR(45) NULL,
  `receive` DATETIME NULL,
  `personality` TEXT(300) NULL,
  `rating` INT NULL,
  `IsReturn` TINYINT NULL,
  `user_id` INT NOT NULL,
  `orderTable_id` INT(11) NOT NULL,
  `sendingStatus` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_user1_idx` (`user_id` ASC),
  INDEX `fk_payment_orderTable1_idx` (`orderTable_id` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `id10884474_catering`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_orderTable1`
    FOREIGN KEY (`orderTable_id`)
    REFERENCES `id10884474_catering`.`orderTable` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id10884474_catering`.`transfer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id10884474_catering`.`transfer` ;

CREATE TABLE IF NOT EXISTS `id10884474_catering`.`transfer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Isconfirm` DATETIME NULL,
  `senderTimeDate` DATETIME NULL,
  `payment_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `Isget` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transfer_payment1_idx` (`payment_id` ASC),
  INDEX `fk_transfer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_transfer_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `id10884474_catering`.`payment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `id10884474_catering`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
